spring:
  application:
    name: twitter-to-kafka-service

  profiles:
    active: twitter_to_kafka

  cloud:
    config:
      name: config-client-twitter_to_kafa

  config:
   import: configserver:http://localhost:8888

#  security:
#    user:
#      name: spring_cloud_user
#      password: springCloud_Pwd!
